FROM maven:3.9.6-eclipse-temurin-17-alpine
WORKDIR /app

# Descargar dependencias para cachear la capa
COPY pom.xml .
RUN mvn dependency:go-offline -B

# Copiar el código fuente
COPY src ./src

EXPOSE 8080

CMD ["mvn", "spring-boot:run", "-Dmaven.test.skip=true"]
